[awesomewm]
src.git = "https://github.com/awesomeWM/awesome"
fetch.github = "awesomeWM/awesome"

[picom]
src.git = "https://github.com/yshui/picom"
fetch.github = "yshui/picom"

[wezterm]
src.git = "https://github.com/wez/wezterm"
fetch.git = "https://github.com/wez/wezterm.git"
git.fetchSubmodules = true

[zsh-nix-shell]
src.git = "https://github.com/chisui/zsh-nix-shell"
fetch.git = "https://github.com/chisui/zsh-nix-shell.git"

[powerlevel10k]
src.git = "https://github.com/romkatv/powerlevel10k"
fetch.git = "https://github.com/romkatv/powerlevel10k.git"

[themixgui]
src.git = "https://github.com/themix-project/themix-gui"
fetch.git = "https://github.com/themix-project/themix-gui.git"
git.fetchSubmodules = true

[stfork]
src.git = "https://github.com/LukeSmithxyz/st"
fetch.git = "https://github.com/LukeSmithxyz/st.git"

[rtl8812au]
src.git = "https://github.com/aircrack-ng/rtl8812au"
fetch.git = "https://github.com/aircrack-ng/rtl8812au.git"

[yuzu]
src.git = "https://github.com/yuzu-emu/yuzu-mainline"
fetch.git = "https://github.com/yuzu-emu/yuzu-mainline.git"
git.fetchSubmodules = true

[yuzu-compat-list]
src.manual = "https://github.com/flathub/org.yuzu_emu.yuzu"
fetch.url = "https://github.com/flathub/org.yuzu_emu.yuzu/blob/master/compatibility_list.json"

[aseprite]
src.github_tag = "aseprite/aseprite"
fetch.github = "aseprite/aseprite"
git.fetchSubmodules = true
