[tool.poetry]
name = "poetry-app"
version = "0.1.0"
description = ""
authors = ["sachinrawat544 <sachin@bmconsulting.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
