# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aseprite = {
    pname = "aseprite";
    version = "v1.3.7";
    src = fetchFromGitHub {
      owner = "aseprite";
      repo = "aseprite";
      rev = "v1.3.7";
      fetchSubmodules = true;
      sha256 = "sha256-75kYJXmyags0cW2D5Ksq1uUrFSCAkFOdmn7Ya/6jLXc=";
    };
  };
  awesomewm = {
    pname = "awesomewm";
    version = "ad0290bc1aac3ec2391aa14784146a53ebf9d1f0";
    src = fetchFromGitHub {
      owner = "awesomeWM";
      repo = "awesome";
      rev = "ad0290bc1aac3ec2391aa14784146a53ebf9d1f0";
      fetchSubmodules = false;
      sha256 = "sha256-uaskBbnX8NgxrprI4UbPfb5cRqdRsJZv0YXXshfsxFU=";
    };
    date = "2024-06-06";
  };
  picom = {
    pname = "picom";
    version = "452aa751875bc86799895c941e121b1f0041b0af";
    src = fetchFromGitHub {
      owner = "yshui";
      repo = "picom";
      rev = "452aa751875bc86799895c941e121b1f0041b0af";
      fetchSubmodules = false;
      sha256 = "sha256-K+haDRtSN9XK99+ZKfj0QoW2pF0LOBfDiZp+n8EuP6k=";
    };
    date = "2024-06-21";
  };
  powerlevel10k = {
    pname = "powerlevel10k";
    version = "bde5ca4c2aa6e0c52dd7f15cf216dffdb1ec788c";
    src = fetchgit {
      url = "https://github.com/romkatv/powerlevel10k.git";
      rev = "bde5ca4c2aa6e0c52dd7f15cf216dffdb1ec788c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-IA2pPW8WT/9/jz/+5zDwedkYz+rzyCy0DRnIvDh9zac=";
    };
    date = "2024-05-21";
  };
  stfork = {
    pname = "stfork";
    version = "36d225d71d448bfe307075580f0d8ef81eeb5a87";
    src = fetchgit {
      url = "https://github.com/LukeSmithxyz/st.git";
      rev = "36d225d71d448bfe307075580f0d8ef81eeb5a87";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-u8E8/aqbL3T4Sz0olazg7VYxq30haRdSB1SRy7MiZiA=";
    };
    date = "2022-10-01";
  };
  themixgui = {
    pname = "themixgui";
    version = "c1e0d5a7b8c227eda717faebf74b1ffa72c15058";
    src = fetchgit {
      url = "https://github.com/themix-project/themix-gui.git";
      rev = "c1e0d5a7b8c227eda717faebf74b1ffa72c15058";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-OTTD/ArwPLtzaxCHcJrW19B0EgurmHCc4g/iJXigCD0=";
    };
    date = "2024-06-21";
  };
  wezterm = {
    pname = "wezterm";
    version = "cb1406860a23896ca6935696169644d140e29208";
    src = fetchgit {
      url = "https://github.com/wez/wezterm.git";
      rev = "cb1406860a23896ca6935696169644d140e29208";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-5BsbCoK6JYcDKlnzVEvB+ivNt51rYDySUoYb4L9bYFc=";
    };
    date = "2024-06-17";
  };
  zsh-nix-shell = {
    pname = "zsh-nix-shell";
    version = "82ca15e638cc208e6d8368e34a1625ed75e08f90";
    src = fetchgit {
      url = "https://github.com/chisui/zsh-nix-shell.git";
      rev = "82ca15e638cc208e6d8368e34a1625ed75e08f90";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Rtg8kWVLhXRuD2/Ctbtgz9MQCtKZOLpAIdommZhXKdE=";
    };
    date = "2023-12-31";
  };
}
