# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  awesomewm = {
    pname = "awesomewm";
    version = "aa8c7c6e27a20fa265d3f06c5dc3fe72cc5f021e";
    src = fetchFromGitHub ({
      owner = "awesomeWM";
      repo = "awesome";
      rev = "aa8c7c6e27a20fa265d3f06c5dc3fe72cc5f021e";
      fetchSubmodules = false;
      sha256 = "sha256-DGAImB4u8sRP9PEoZ4YXAxopa8eaJ7YJxSiBh36yfaE=";
    });
  };
  picom = {
    pname = "picom";
    version = "751f30578e352f6cd37fc63cbf4643e47ab3587a";
    src = fetchFromGitHub ({
      owner = "yshui";
      repo = "picom";
      rev = "751f30578e352f6cd37fc63cbf4643e47ab3587a";
      fetchSubmodules = false;
      sha256 = "sha256-HdsDGc5bxslP048YLv7p6RMB3kG57b4TxlzhM5IarVs=";
    });
  };
  wezterm = {
    pname = "wezterm";
    version = "5e0fd1a06e10d23e2a61696d0b0ebdacffecb661";
    src = fetchgit {
      url = "https://github.com/wez/wezterm.git";
      rev = "5e0fd1a06e10d23e2a61696d0b0ebdacffecb661";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-B3ZsF9IDrZzB573NcpWHPM+Ss5YjV8LDRLjce8RZJd0=";
    };
  };
}
